name: plant_disease_detection
channels:
  - conda-forge
  - pytorch
  - fastai
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Deep Learning Framework
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - torchaudio>=0.12.0
  # Note: CUDA not available on macOS - using CPU version
  
  # Computer Vision & Image Processing
  - opencv>=4.6.0
  - pillow>=9.0.0
  - scikit-image>=0.19.0
  
  # Data Science & ML
  - numpy>=1.21.0
  - pandas>=1.4.0
  - scikit-learn>=1.1.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Jupyter & Development
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - notebook>=6.4.0
  
  # API & Web Framework
  - fastapi>=0.78.0
  - uvicorn>=0.18.0
  - python-multipart>=0.0.5
  
  # Utilities
  - tqdm>=4.64.0
  - pyyaml>=6.0
  - requests>=2.28.0
  
  # Pip dependencies (will be installed after conda)
  - pip
  - pip:
    # Additional ML libraries
    - tensorboard>=2.9.0
    - wandb>=0.12.0  # For experiment tracking
    - albumentations>=1.2.0  # Advanced data augmentation
    - timm>=0.6.0  # Pre-trained models
    - efficientnet-pytorch>=0.7.1
    
    # Model export & optimization
    - onnx>=1.12.0
    - onnxruntime>=1.12.0
    
    # Grad-CAM for explainability
    - grad-cam>=1.4.0
    
    # Data validation
    - great-expectations>=0.15.0
    
    # Monitoring & logging
    - mlflow>=1.28.0
    - prometheus-client>=0.14.0
    
    # Development tools
    - black>=22.0.0
    - flake8>=4.0.0
    - pytest>=7.0.0
    - pre-commit>=2.19.0
